<a href="https://colab.research.google.com/github/Nirdesh-arc/Nirdesh_Khadka_Concept_and_Tech_of_AI/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr_empty = np.empty((2, 2))
print("1. Empty 2x2 array:\n", arr_empty)


# 2. Initialize an all-one array with size 4x2
arr_ones = np.ones((4, 2))
print("\n2. All ones 4x2 array:\n", arr_ones)


# 3. Return a new array of given shape and type, filled with a fill value
arr_full = np.full((3, 3), 7)  # Example: fill with 7
print("\n3. Full 3x3 array filled with 7:\n", arr_full)


# 4. Return a new array of zeros with same shape and type as a given array
a = np.array([[1, 2], [3, 4]])
arr_zeros_like = np.zeros_like(a)
print("\n4. Zeros like given array a:\n", arr_zeros_like)


# 5. Return a new array of ones with same shape and type as a given array
b = np.array([[5, 6], [7, 8]])
arr_ones_like = np.ones_like(b)
print("\n5. Ones like given array b:\n", arr_ones_like)


# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\n6. Array from list:\n", arr_from_list)

1. Empty 2x2 array:
 [[4.28330912e-315 0.00000000e+000]
 [4.28428305e-315 6.75328897e-310]]

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full 3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array a:
 [[0 0]
 [0 0]]

5. Ones like given array b:
 [[1 1]
 [1 1]]

6. Array from list:
 [1 2 3 4]


In [ ]:
# 1. Create an array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array 10 to 49:\n", arr_range)

# 2. Create a 3x3 matrix with values from 0 to 8
arr_matrix = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix 0 to 8:\n", arr_matrix)

# 3. Create a 3x3 identity matrix
identity = np.eye(3)
print("\n3. Identity Matrix:\n", identity)

# 4. Create a random array of size 30 and find the mean
rand_arr = np.random.random(30)
print("\n4. Mean of random 30 values:", rand_arr.mean())

# 5. Create a 10x10 random array and find min & max
rand_10x10 = np.random.random((10, 10))
print("\n5. Min:", rand_10x10.min(), " Max:", rand_10x10.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr_zero = np.zeros(10)
arr_zero[4] = 1
print("\n6. Zero array with 5th element = 1:\n", arr_zero)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
rev_arr = arr[::-1]
print("\n7. Reversed array:\n", rev_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n8. Border 1, inside 0:\n", border)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", checkerboard)

1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random 30 values: 0.5943515875747015

5. Min: 0.0009867308345610226  Max: 0.999074631560462

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. Border 1, inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. Addition:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. Subtraction:\n", sub_xy)

# 3. Multiply the array with an integer (example: multiply x by 3)
mul_x = x * 3
print("\n3. x multiplied by 3:\n", mul_x)

# 4. Square of each element of array x
square_x = x ** 2
print("\n4. Square of x:\n", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
print("\n5(a). Dot product v·w =", dot_vw)

dot_xv = np.dot(x, v)
print("\n5(b). Dot product x·v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("\n5(c). Dot product x·y:\n", dot_xy)

# 6. Concatenate x and y along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6(a). Concatenate x & y along rows:\n", concat_xy_row)

# Concatenate v and w along columns
concat_vw_col = np.column_stack((v, w))
print("\n6(b). Concatenate v & w along columns:\n", concat_vw_col)

# 7. Concatenate x and v (observe error and fix)
try:
    try_concat = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x & v:\n", try_concat)
except ValueError as e:
    print("\n7. Error while concatenating x & v:", e)

# Correct concatenation after reshaping v
correct_concat = np.concatenate((x, v.reshape(1, 2)), axis=0)
print("\nCorrect concatenation (after reshape):\n", correct_concat)

1. Addition:
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of x:
 [[ 1  4]
 [ 9 25]]

5(a). Dot product v·w = 219

5(b). Dot product x·v:
 [29 77]

5(c). Dot product x·y:
 [[19 22]
 [50 58]]

6(a). Concatenate x & y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6(b). Concatenate v & w along columns:
 [[ 9 11]
 [10 12]]

7. Error while concatenating x & v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Correct concatenation (after reshape):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
import numpy as np

# -------------------------------------------------------
# 1. Prove A * A^-1 = I
# -------------------------------------------------------

A = np.array([[3, 4],
              [7, 8]])

print("Matrix A:")
print(A)

A_inv = np.linalg.inv(A)
print("\nInverse of A:")
print(A_inv)

identity_check = A.dot(A_inv)
print("\nA * A_inv (Should be Identity Matrix):")
print(identity_check)


# -------------------------------------------------------
# 2. Prove AB != BA
# -------------------------------------------------------

B = np.array([[5, 3],
              [2, 1]])

print("\nMatrix B:")
print(B)

AB = A.dot(B)
BA = B.dot(A)

print("\nAB =")
print(AB)

print("\nBA =")
print(BA)

print("\nIs AB equal to BA? ->", np.array_equal(AB, BA))


# -------------------------------------------------------
# 3. Prove (AB)^T = B^T A^T
# -------------------------------------------------------

left = (A.dot(B)).T
right = B.T.dot(A.T)

print("\n(AB)^T =")
print(left)

print("\nB^T A^T =")
print(right)

print("\nIs (AB)^T equal to B^T A^T? ->", np.array_equal(left, right))


# -------------------------------------------------------
# 4. Solve the system of linear equations
#
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
#
# Using inverse method
# -------------------------------------------------------

A2 = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B2 = np.array([-1, -3, 9])

print("\n\nCoefficient Matrix A2:")
print(A2)

print("\nConstant Matrix B2:")
print(B2)

A2_inv = np.linalg.inv(A2)
solution1 = A2_inv.dot(B2)

print("\nSolution using Inverse Method (A^-1 * B):")
print("x =", solution1[0])
print("y =", solution1[1])
print("z =", solution1[2])


# -------------------------------------------------------
# 5. Solve using np.linalg.solve (recommended method)
# -------------------------------------------------------

solution2 = np.linalg.solve(A2, B2)

print("\nSolution using numpy.linalg.solve:")
print("x =", solution2[0])
print("y =", solution2[1])
print("z =", solution2[2])


Matrix A:
[[3 4]
 [7 8]]

Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inv (Should be Identity Matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Matrix B:
[[5 3]
 [2 1]]

AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]

Is AB equal to BA? -> False

(AB)^T =
[[23 51]
 [13 29]]

B^T A^T =
[[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T? -> True


Coefficient Matrix A2:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant Matrix B2:
[-1 -3  9]

Solution using Inverse Method (A^-1 * B):
x = 2.0
y = 1.0
z = -2.0

Solution using numpy.linalg.solve:
x = 2.0
y = 1.0000000000000002
z = -2.0


AttributeError: 'str' object has no attribute 'arr_matrix'